name: CMake

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
    - name: Config
      run: cmake -S . -B build
    - name: Compile
      run: cmake --build build
    - name: Tests
      run: ctest --test-dir build --output-on-failure
